version: 2

builds:
  - id: spacelift-intent
    main: ./cmd/spacelift-intent
    binary: spacelift-intent
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: [-trimpath, -v]
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]

archives:
  - id: default
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  use: github-native

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Spacelift Intent MCP Server {{ .Version }}

    Release artifacts for all supported platforms.

  footer: |
    **Full Changelog**: https://github.com/spacelift-io/spacelift-intent/compare/{{ .PreviousTag }}...{{ .Tag }}
